import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { SITE_DATA } from "@/lib/siteData";
import { headers } from "next/headers";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const h = await headers(); // ✅ MUST await in Next 16
  
    const domain = h.get("host") || "localhost";
  
    const pageData =
      SITE_DATA.find((item) => item.domain === domain) ||
      SITE_DATA[0]; // fallback
    
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Navbar/>
        {children}
         <Footer data={pageData?.footer}/>

      </body>
    </html>
  );
}
