export const GOOGLE_VERIFICATION = {
  "www.flatsforsaleinhisar.com": "3vF9ESnurvBS1s5ksxMnUrl5UI8VYUln0Kg_k1JiXAk",
  "www.flatsforrentinhisar.com": "I6VatZOXsoEtR7wJXeVkkL3WCzPPl4wj02ytBiFh4NA",
  "www.houseforsaleinhisar.com": "MSIZ_p9iTeHQ4NjyZMhXI-Ju0XW8gmENrJ9zdudhG14",
  "www.houseforrentinhisar.com": "lfRypTXttgKSnsKCj0PjJAbjxNBAff78cuRKXBhJaVs",
  "www.shopforsaleinhisar.com": "w4_NPNL3zdfXsId38Ut22hHgaC2yci9uqffcGHVHW0s",
  "www.commercialpropertyforsaleinhisar.com": "W6_fwXJ_sKaOpIWculaOGUOauUDAfOd2hmNB3_zHxt8",
  "www.shopforrentinhisar.com": "nmb2gAsTXmT4LTrIUKdbx3BomGxbRBdRzVESZ-4p-Is",
  "www.plotforsaleinhisar.com": "W_o3oODv82OrjKM8fkosmi93ZzGnrVVRc9ak0Bc0oBw",
  "www.agriculturelandforsaleinhisar.com": "I98IU-vVf-KkdXixol6X08B1doFYKFwd1xWhd5ufjyM",
  "www.toletserviceinhisar.com": "P0iJWYoRrnasQY-TGwQyaVdAP_TxjW4Wz8wXJ9X1Z7A",
  "www.buyhouseinfaridabad.com": "0qD-omcB7nluQBHQVolq7EjbHHewk_HPODkTkAOKFI0",
  "www.3bhkflatforsaleinfaridabad.com": "gBZtXnn8cEaivGv490vpWS-W7UD5Ho6GGgpVSVr1efE",
   "www.buyhouseinfaridabad.com": "",
  "www.houseforsaleinfaridabad.com": "",
  "www.renthouseinfaridabad.com": "",
  "www.worldstreetfaridabad.com": "",
  "www.affordablehouseinfaridabad.com": "",
  "www.3bhkflatforsaleinfaridabad.com": "GTM-KZT7TMZH",
  "www.shopforsaleinfaridabad.com": "",
  "www.flatforrentinfaridabad.com": "",
  "www.plotforsaleinfaridabad.com": "",
  "www.agriculturelandforsaleinfaridabad.com": "",
  "www.shopforrentinfaridabad.com": "",
  "www.residentialprojectsinfaridabad.com": "",
  "www.officespaceforrentinfaridabad.com": "",
  "www.realestateprojectsinfaridabad.com": "",
  "www.houseforrentinfaridabad.com": "",
  "www.builderfloorforsaleinfaridabad.com": "",
  "www.residentialpropertyinfaridabad.com": "",
  "www.2bhkflatforsaleinfaridabad.com": "",
  "www.flatforsaleinfaridabad.com": "",
  "www.realestateagentsinfaridabad.com": "",
  "www.commercialprojectsinfaridabad.com": "",
  "www.officespaceforsaleinfaridabad.com": "",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",

  "gurgaon.projectwallah.live": "GSC_CODE_GURGAON",

  // fallback
  "localhost": "GSC_CODE_DEFAULT",
};
