export const GOOGLE_VERIFICATION = {
  "www.flatsforsaleinhisar.com": "3vF9ESnurvBS1s5ksxMnUrl5UI8VYUln0Kg_k1JiXAk",
  "www.flatsforrentinhisar.com": "I6VatZOXsoEtR7wJXeVkkL3WCzPPl4wj02ytBiFh4NA",
  "www.houseforsaleinhisar.com": "MSIZ_p9iTeHQ4NjyZMhXI-Ju0XW8gmENrJ9zdudhG14",
  "www.houseforrentinhisar.com": "lfRypTXttgKSnsKCj0PjJAbjxNBAff78cuRKXBhJaVs",
  "www.shopforsaleinhisar.com": "w4_NPNL3zdfXsId38Ut22hHgaC2yci9uqffcGHVHW0s",
  "www.commercialpropertyforsaleinhisar.com": "W6_fwXJ_sKaOpIWculaOGUOauUDAfOd2hmNB3_zHxt8",
  "www.shopforrentinhisar.com": "nmb2gAsTXmT4LTrIUKdbx3BomGxbRBdRzVESZ-4p-Is",
  "www.plotforsaleinhisar.com": "W_o3oODv82OrjKM8fkosmi93ZzGnrVVRc9ak0Bc0oBw",
  "www.agriculturelandforsaleinhisar.com": "I98IU-vVf-KkdXixol6X08B1doFYKFwd1xWhd5ufjyM",
  "www.toletserviceinhisar.com": "P0iJWYoRrnasQY-TGwQyaVdAP_TxjW4Wz8wXJ9X1Z7A",
  "www.buyhouseinfaridabad.com": "0qD-omcB7nluQBHQVolq7EjbHHewk_HPODkTkAOKFI0",
  "www.houseforsaleinfaridabad.com": "",
  "www.renthouseinfaridabad.com": "",
  "www.worldstreetfaridabad.in": "",
  "www.affordablehouseinfaridabad.com": "",
  "www.3bhkflatforsaleinfaridabad.com": "gBZtXnn8cEaivGv490vpWS-W7UD5Ho6GGgpVSVr1efE",
  "www.shopforsaleinfaridabad.com": "l4WO-jQ23FAqBxf9YwhJmpvENtaTrRDoPZzRXZs27I8",
  "www.flatforrentinfaridabad.com": "KbN6Un0-lo9xLpZwD6VmBbDPDqZUVQOgEE-xU33dnQo",
  "www.plotforsaleinfaridabad.com": "aUiy8S2C1WBMsr7rN6gIvWiLxKnnwDBUuq1LHRVm1Q4",
  "www.agriculturelandforsaleinfaridabad.com": "LBGqLG7P8HWCgyE0EK6vcxDCcKM_uS9Z1cqxM-qfJx8",
  "www.shopforrentinfaridabad.com": "YNNA946qmPRr-zBq3b5brFoZ4T91q44hpnPrK3mZeIM",
  "www.residentialprojectsinfaridabad.com": "XWsx1s9v_iV-8S0q8i2RscX6e55dTKropYiOYd9Ahac",
  "www.officespaceforrentinfaridabad.com": "YQJTg7iLM9YjUJo_jHJpdvE4de1uQGZ9SFifVMdJmr4",
  "www.realestateprojectsinfaridabad.com": "",
  "www.houseforrentinfaridabad.com": "Zsows2a-l9vUGF56PjbvMZ0aEbvne1OYKGRsv-rt2e",
  "www.builderfloorforsaleinfaridabad.com": "sPMYb1NK_mAKwNR2V1lt8YyWgCYQqy1F_maOkqjHulI",
  "www.residentialpropertyinfaridabad.com": "arTkB7qpKhJgAAKDJ2oilHtfnD6eBpIGYEXU_ZJzw_k",
  "www.2bhkflatforsaleinfaridabad.com": "zgfDPiMIo0YirnnCBh11yE6FHbeWYAAnbU7ONAWkMe4",
  "www.flatforsaleinfaridabad.com": "EF7KSGP9xuFSEE82kesSUjGI3xdi5YRmpyRHBcAJjNg",
  "www.realestateagentsinfaridabad.com": "",
  "www.commercialprojectsinfaridabad.com": "FhW6i1yedcpAQgs1pcj-3y4ptv-HCc4AonrEHWRifVs",
  "www.officespaceforsaleinfaridabad.com": "",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",
  "faridabad.projectwallah.live": "GSC_CODE_FARIDABAD",

  "gurgaon.projectwallah.live": "GSC_CODE_GURGAON",
  "www.houseforsaleingurgaon.com": "pHqr6Bsv15OUaXFBBfX15XFMiNhSBoLkYt3wO0gcxYY",

  // fallback
  "localhost": "GSC_CODE_DEFAULT",
};
