export const GTM_IDS = {
  "www.flatsforsaleinhisar.com": "GTM-NL4P6JP3",
  "www.flatsforrentinhisar.com": "GTM-MD7W3G3K",
  "www.houseforsaleinhisar.com": "GTM-PP7Z5FNP",
  "www.houseforrentinhisar.com": "GTM-N9FW6DJH",
  "www.shopforsaleinhisar.com": "GTM-WDRGJWQK",
  "www.commercialpropertyforsaleinhisar.com": "GTM-TN557WPL",
  "www.shopforrentinhisar.com": "GTM-PN34LFRG",
  "www.plotforsaleinhisar.com": "GTM-NVSFJW29",
  "www.agriculturelandforsaleinhisar.com": "GTM-5LSM6QDJ",
  "www.toletserviceinhisar.com": "GTM-KS7WBPQ8",
  "www.buyhouseinfaridabad.com": "",
  "www.houseforsaleinfaridabad.com": "",
  "www.renthouseinfaridabad.com": "",
  "www.worldstreetfaridabad.in": "GTM-TQ5343RR",
  "www.affordablehouseinfaridabad.com": "",
  "www.3bhkflatforsaleinfaridabad.com": "GTM-KZT7TMZH",
  "www.shopforsaleinfaridabad.com": "GTM-T2VVCXVR",
  "www.flatforrentinfaridabad.com": "GTM-M49TKK4Z",
  "www.plotforsaleinfaridabad.com": "GTM-5WFX3DZQ",
  "www.agriculturelandforsaleinfaridabad.com": "GTM-NRJ4ZF9B",
  "www.shopforrentinfaridabad.com": "GTM-WKVXQXKP",
  "www.residentialprojectsinfaridabad.com": "GTM-59FT4H5C",
  "www.officespaceforrentinfaridabad.com": "GTM-MQTSCKVK",
  "www.realestateprojectsinfaridabad.com": "",
  "www.houseforrentinfaridabad.com": "GTM-5TG9SB2M",
  "www.builderfloorforsaleinfaridabad.com": "GTM-NP958N6M",
  "www.residentialpropertyinfaridabad.com": "GTM-K9G492WC",
  "www.2bhkflatforsaleinfaridabad.com": "",
  "www.flatforsaleinfaridabad.com": "GTM-KKPVN4QN",
  "www.realestateagentsinfaridabad.com": "",
  "www.commercialprojectsinfaridabad.com": "GTM-NMX63GPH",
  "www.officespaceforsaleinfaridabad.com": "GTM-TPLHR8N3",
  

  // fallback (localhost / default)
  "localhost": "GTM-NL446123",
};
